name: build-on-schedule

run-name: Build using schedule - ${{ github.actor }}

on: [push]
# on:
#   schedule:
#     - cron: '30 14 * * *'   # every day at 2:30pm

env:
  REGISTRY_USER: ${{ secrets.QUAY_USER }}
  IMAGE_REGISTRY: quay.io
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASS }}
  REPO_OWNER: ${{ vars.REPO_OWNER }}

jobs:
  setup-keycloak-base-image:
    runs-on: ubuntu-latest
    environment: keycloak_base_image
    steps:
      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Checkout Keycloak 22 branch
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_OWNER }}/keycloak-test
          ref: keycloak-22

      - name: Get status and remote
        shell: bash
        run: |
          status="$(git status)"
          remote="$(git remote -v)"
          echo "TEST_VALUE<<EOF" >> $GITHUB_ENV
          echo "status=${status}" >> $GITHUB_ENV
          echo "remote=${remote}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          tag="$( echo base-image-`date +\"%Y-%m-%d_%H_%M_%S\"`-${{ github.run_id }} )"
          echo "KEYCLOAK_22_TAG=${tag}" >> $GITHUB_ENV

      - name: Print current tag and status
        shell: bash
        run: |
          echo "VALUES=${{ env.TEST_VALUE }}"
          echo "KEYCLOAK_22_TAG=${{ env.KEYCLOAK_22_TAG }}"

      # - name: Build with Maven - skipping all the tests
      #   run: mvn clean install -DskipTestsuite -DskipExamples -DskipTests

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Create and push tag
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}-github-actions[bot]@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}-github-actions[bot]"
          git tag -a ${{ env.KEYCLOAK_22_TAG }} -m 'Base image tag'
          git push origin refs/tags/${{ env.KEYCLOAK_22_TAG }}
