# This action requires following configuration variables/secrets:
#  Secrets:
#   - QUAY_USER
#   - QUAY_PASS
#  Variables:
#   - REPO_OWNER
#   - IMAGE_NAME
#   - IMAGE_TAG
#   - KEYCLOAK_VERSION


name: build-on-schedule

run-name: Build using schedule - ${{ github.actor }}

on: [push, workflow_dispatch]
# on:
#   schedule:
#     - cron: '30 14 * * *'   # every day at 2:30pm

env:
  REGISTRY_USER: ${{ secrets.QUAY_USER }}
  IMAGE_REGISTRY: quay.io
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASS }}
  REPO_OWNER: ${{ vars.REPO_OWNER }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}
  KEYCLOAK_VERSION: ${{ vars.KEYCLOAK_VERSION }}

jobs:
  setup-keycloak-base-image:
    runs-on: ubuntu-latest
    environment: keycloak_base_image
    steps:
      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Checkout Keycloak 22 branch
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_OWNER }}/keycloak-test
          ref: keycloak-22
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get status and remote
        shell: bash
        run: |
          status="$(git status)"
          remote="$(git remote -v)"
          echo "TEST_VALUE<<EOF" >> $GITHUB_ENV
          echo "status=${status}" >> $GITHUB_ENV
          echo "remote=${remote}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          tag="$( echo base-image-`date +"%Y-%m-%d_%H_%M_%S"`-${{ github.run_id }} )"
          echo "KEYCLOAK_22_TAG=${tag}" >> $GITHUB_ENV

      - name: Print current tag and status
        shell: bash
        run: |
          echo "VALUES=${{ env.TEST_VALUE }}"
          echo "KEYCLOAK_22_TAG=${{ env.KEYCLOAK_22_TAG }}"

      - name: Build with Maven - skipping all the tests
        run: mvn clean install -DskipTestsuite -DskipExamples -DskipTests

      - name: Create and push tag
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}-github-actions[bot]@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}-github-actions[bot]"
          git tag -a ${{ env.KEYCLOAK_22_TAG }} -m 'Base image tag'
          echo "git push origin refs/tags/${{ env.KEYCLOAK_22_TAG }}" >>  $GITHUB_STEP_SUMMARY

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Copy tarfile for building base image
        working-directory: ./quarkus/container
        run: |
          cp ../dist/target/keycloak-${{ env.KEYCLOAK_VERSION }}.tar.gz .
          echo "Current dir: `pwd`" >> $GITHUB_STEP_SUMMARY
          ls -l *.gz >> $GITHUB_STEP_SUMMARY

      - name: Build base-image from source
        id: build_base_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          context: ./quarkus/container
          containerfiles: |
            ./quarkus/container/Dockerfile
          build-args: |
            KEYCLOAK_DIST=keycloak-${{ env.KEYCLOAK_VERSION }}.tar.gz

      - name: Print base-image build info
        run: |
          echo "Built Keycloak-22 image - ${{ steps.build_base_image.outputs.image-with-tag }}" >>  $GITHUB_STEP_SUMMARY

      - name: Push base-image
        id: push_base_image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_base_image.outputs.image }}
          tags: ${{ steps.build_base_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USER }}

      - name: Print base-image info
        run: |
          echo "Pushed Keycloak-22 image to ${{ steps.push_base_image.outputs.registry-paths }}" >>  $GITHUB_STEP_SUMMARY
          echo "With digest ${{ steps.push_base_image.outputs.digest }}" >>  $GITHUB_STEP_SUMMARY

