# This action requires following configuration variables/secrets:
#  Secrets:
#   - QUAY_USER
#   - QUAY_PASS
#  Variables:
#   - REPO_OWNER
#   - IMAGE_NAME
#   - IMAGE_TAG
#   - KEYCLOAK_VERSION


name: build-on-demand

run-name: Build base-image on demand - ${{ github.actor }}

on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash

env:
  EMAIL_SENDER: ${{ vars.EMAIL_SENDER_NAME }}
  EMAIL_SEND_TO_LIST: ${{ vars.CREATE_IMAGE_NOTIFIERS }}
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASS }}
  REGISTRY_USER: ${{ vars.QUAY_USER }}
  REGISTRY_REPO_OWNER: ${{ vars.QUAY_REPO_OWNER }}
  IMAGE_REGISTRY: quay.io
  REPO_OWNER: ${{ vars.REPO_OWNER }}
  REPO_BRANCH: ${{ vars.REPO_BRANCH }}
  REPO_NAME: ${{ vars.REPO_NAME }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}
  KEYCLOAK_VERSION: ${{ vars.KEYCLOAK_VERSION }}
  WORKFLOW_USER: "${{ github.actor }}${{ vars.WORKFLOW_USER_SUFFIX }}"
  WORKFLOW_EMAIL: "${{ github.actor }}${{ vars.WORKFLOW_USER_SUFFIX }}@${{ vars.WORKFLOW_EMAIL_DOMAIN }}"


jobs:
  setup-keycloak-base-image:
    runs-on: ubuntu-latest
    environment: keycloak_base_image

    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout Keycloak 22 branch
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}
          ref: ${{ env.REPO_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get status and remote
        run: |
          status="$(git status)"
          remote="$(git remote -v)"
          echo "TEST_VALUE<<EOF" >> $GITHUB_ENV
          echo "status=${status}" >> $GITHUB_ENV
          echo "remote=${remote}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          tag="$( echo base-image-`date +"%Y-%m-%d_%H_%M_%S"`-${{ github.run_id }} )"
          echo "KEYCLOAK_22_TAG=${tag}" >> $GITHUB_ENV

      - name: Print current tag and status
        run: |
          echo "VALUES=${{ env.TEST_VALUE }}"
          echo "KEYCLOAK_22_TAG=${{ env.KEYCLOAK_22_TAG }}"

      - name: Build with Maven - skipping all the tests
        run: mvn clean install -DskipTestsuite -DskipExamples -DskipTests

      - name: Setup Git Config
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ env.WORKFLOW_EMAIL }}"
          git config --global user.name "${{ env.WORKFLOW_USER }}"

      - name: Create tag
        run: |
          git tag -a ${{ env.KEYCLOAK_22_TAG }} -m 'Base image tag'

      - name: Push tag
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Pushing the newly created git tag - ${{ env.KEYCLOAK_22_TAG }}" >>  $GITHUB_STEP_SUMMARY
          # git push origin refs/tags/${{ env.KEYCLOAK_22_TAG }}

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Copy tarfile for building base image
        working-directory: ./quarkus/container
        run: |
          cp ../dist/target/keycloak-${{ env.KEYCLOAK_VERSION }}.tar.gz .
          echo "Current dir: `pwd`" >> $GITHUB_STEP_SUMMARY
          ls -l *.gz >> $GITHUB_STEP_SUMMARY

      - name: Print base-image tag info
        run: |
          echo "Using tag ${{ env.KEYCLOAK_22_TAG }} to create the base-image" >> $GITHUB_STEP_SUMMARY

      - name: Build base-image from source
        id: build_base_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          context: ./quarkus/container
          containerfiles: |
            ./quarkus/container/Dockerfile
          build-args: |
            KEYCLOAK_DIST=keycloak-${{ env.KEYCLOAK_VERSION }}.tar.gz

      - name: Print base-image build info
        run: |
          echo "* Built Keycloak-22 image - ${{ steps.build_base_image.outputs.image-with-tag }}" >>  $GITHUB_STEP_SUMMARY

      - name: Push base-image
        id: push_base_image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_base_image.outputs.image }}
          tags: ${{ steps.build_base_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_REPO_OWNER }}

      - name: Print base-image info
        run: |
          echo "* Pushed Keycloak-22 image to ${{ env.IMAGE_REGISTRY }}" >>  $GITHUB_STEP_SUMMARY
          echo "* Image info:" >>  $GITHUB_STEP_SUMMARY
          echo "  * path: ${{ steps.push_base_image.outputs.registry-path }}" >>  $GITHUB_STEP_SUMMARY
          echo "  * digest: ${{ steps.push_base_image.outputs.digest }}" >>  $GITHUB_STEP_SUMMARY        

      - name: Send email with base-image info
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          subject: New Keycloak base-image is available - TEST
          to: ${{ env.EMAIL_SEND_TO_LIST }}
          from: ${{ env.EMAIL_SENDER }}
          reply_to: ${{ env.WORKFLOW_EMAIL }}
          html_body: |
            Workflow ${{ github.job }} of ${{github.repository}} triggered by ${{ github.actor }} has successfully built and pushed a new Keycloak base-image.
              
            New base-image information is given below:
              * Registry: ${{ env.IMAGE_REGISTRY }}
              * Path: ${{ steps.push_base_image.outputs.registry-path }}
              * Digest: ${{ steps.push_base_image.outputs.digest }}

            Workflow run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          convert_markdown: true
