name: build-on-schedule
run-name: Build using schedule - ${{ github.actor }}
on: [push]
# on:
#   schedule:
#     - cron: '30 14 * * *'   # every day at 2:30pm
jobs:
  create-keycloak-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Checkout Keycloak 22 branch
        uses: actions/checkout@v3
        with:
          repository: RHEcosystemAppEng/keycloak
          ref: keycloak-22

      - name: Set current tag and status
        shell: bash
        run: |
          status="$(git status)"
          remote="$(git remote -v)"
          echo "TEST_VALUE<<EOF" >> $GITHUB_ENV
          echo "status=${status}" >> $GITHUB_ENV
          echo "remote=${remote}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Print current tag and status
        shell: bash
        run: |
          echo "VALUES=${{ env.TEST_VALUE }}"

      # - name: Build with Maven - skipping all the tests
      #   run: mvn clean install -DskipTestsuite -DskipExamples -DskipTests
