# This action requires following configuration variables/secrets:
#  Secrets:
#   - QUAY_USER
#   - QUAY_PASS
#  Variables:
#   - REPO_OWNER
#   - IMAGE_NAME
#   - IMAGE_TAG
#   - KEYCLOAK_VERSION


name: test-git-push

run-name: Testing git push - ${{ github.actor }}

on: [push, workflow_dispatch]

permissions: write-all

defaults:
  run:
    shell: bash

env:
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASS }}
  REGISTRY_USER: ${{ vars.QUAY_USER }}
  IMAGE_REGISTRY: quay.io
  REPO_OWNER: ${{ vars.REPO_OWNER }}
  REPO_NAME: ${{ vars.REPO_NAME }}
  REPO_BRANCH: ${{ vars.REPO_BRANCH }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}
  KEYCLOAK_VERSION: ${{ vars.KEYCLOAK_VERSION }}

jobs:
  test-git-push-tags:
    runs-on: ubuntu-latest
    environment: keycloak_base_image

    steps:
      - name: Print environment info
        run: env

      - name: Checkout Keycloak 22 branch
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}
          ref: ${{ env.REPO_BRANCH }}
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Get status and remote
        run: |
          status="$(git status)"
          remote="$(git remote -v)"
          echo "TEST_VALUE<<EOF" >> $GITHUB_ENV
          echo "status=${status}" >> $GITHUB_ENV
          echo "remote=${remote}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          tag="$( echo base-image-`date +"%Y-%m-%d_%H_%M_%S"`-${{ github.run_id }} )"
          echo "KEYCLOAK_22_TAG=${tag}" >> $GITHUB_ENV

      - name: Print current tag and status
        run: |
          echo "VALUES=${{ env.TEST_VALUE }}"
          echo "KEYCLOAK_22_TAG=${{ env.KEYCLOAK_22_TAG }}"

      - name: Setup Git Config
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}-github-actions[bot]@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}-github-actions[bot]"

      - name: Create tag
        run: |
          git tag -a ${{ env.KEYCLOAK_22_TAG }} -m 'Base image tag'

      - name: Push tag
        run: |
          echo "Pushing the newly created git tag - ${{ env.KEYCLOAK_22_TAG }}" >>  $GITHUB_STEP_SUMMARY
          git push origin refs/tags/${{ env.KEYCLOAK_22_TAG }}
          echo "Using tag ${{ env.KEYCLOAK_22_TAG }} to create the base-image" >> $GITHUB_STEP_SUMMARY
